services:

  m1-da-light-node-celestia-appd:
    image: ghcr.io/movementlabsxyz/m1-da-light-node-celestia-appd:${CONTAINER_REV}
    container_name: m1-da-light-node-celestia-appd
    environment:
      DOT_MOVEMENT_PATH: /.movement
      CELESTIA_RPC_ADDRESS: m1-da-light-node-celestia-appd:26657
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      setup:
        condition: service_healthy
    ports:
      - "26657:26657"
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 26657" ]
      retries: 10
      interval: 10s
      timeout: 5s
    restart: on-failure:3

  m1-da-light-node-celestia-bridge:
    image: ghcr.io/movementlabsxyz/m1-da-light-node-celestia-bridge:${CONTAINER_REV}
    container_name: m1-da-light-node-celestia-bridge
    environment:
      DOT_MOVEMENT_PATH: /.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    ports:
      - "26658:26658"
    depends_on:
      setup:
        condition: service_healthy
      m1-da-light-node-celestia-appd:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 26658" ]
      retries: 10
      interval: 10s
      timeout: 5s
    restart: on-failure:3

  celestia-light-node:
    image: busybox
    container_name: celestia-light-node
    command: sh -c 'echo "Starting Celestia light-node services." && sleep infinity'
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      m1-da-light-node-celestia-appd:
        condition: service_healthy
      m1-da-light-node-celestia-bridge:
        condition: service_healthy
