services:

  suzuka-client-e2e-simple-interaction:
    image: ghcr.io/movementlabsxyz/suzuka-client-e2e-simple-interaction:${CONTAINER_REV}
    container_name: suzuka-client-e2e-simple-interaction
    command: run-simple
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      suzuka-faucet-service: # wait for all of the replicas to be ready
        condition: service_healthy