version: "3"

environment:

processes:

  mcr-client-tests:
    command: |
      set -e
      cargo test -p mcr-settlement-client --features="e2e" test_client_settlement -- --nocapture
    depends_on:
      eth:
        condition: process_healthy
    availability:
      # NOTE: `restart: exit_on_failure` is not needed since
      # exit_on_end implies it.
      exit_on_end: true