[package]
name = "suzuka-full-node"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maptos-dof-execution = { workspace = true }
m1-da-light-node-client = { workspace = true }
m1-da-light-node-util = { workspace = true }
mcr-settlement-client = { workspace = true }
mcr-settlement-manager = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
sha2 = { workspace = true }
tonic = { workspace = true }
movement-types = { workspace = true }
movement-tracing = { workspace = true }
suzuka-config = { workspace = true }
dot-movement = { workspace = true }
godfig = { workspace = true }
tracing-subscriber = { workspace = true }
console-subscriber = { workspace = true }
rocksdb = { workspace = true }
tracing = { workspace = true }
bcs = { workspace = true }
zstd = { workspace = true }

[features]
default = ["mock"]
logging = []
eth = ["mcr-settlement-client/eth", "suzuka-config/eth", "mcr-settlement-manager/eth"]
mock = ["mcr-settlement-client/mock", "suzuka-config/mock", "mcr-settlement-manager/mock"]


[lints]
workspace = true
