[package]
name = "m1-da-light-node-runners"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[[bin]]
name = "m1-da-light-node-celestia-appd"
path = "src/bin/celestia-appd.rs"

[[bin]]
name = "m1-da-light-node-celestia-bridge"
path = "src/bin/celestia-bridge.rs"

[[bin]]
name = "m1-da-light-node-celestia-light"
path = "src/bin/celestia-light.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
commander = { workspace = true }
tracing = { workspace = true }
m1-da-light-node-util = { workspace = true }
dot-movement = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }
tracing-subscriber = { workspace = true }
godfig = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
