[package]
name = "memseq-util"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
futures = { workspace = true }
dot-movement = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
toml = { workspace = true }
godfig = { workspace = true }

[lints]
workspace = true