version: "3"

environment:

processes:

  celestia-node-appd:
    command: |
      m1-da-light-node-celestia-appd
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:26657
    liveness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:26657
    depends_on:
      setup:
        condition: process_healthy

  celestia-bridge:
    command: |
      m1-da-light-node-celestia-bridge
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:26658
    liveness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:26658
    depends_on:
       celestia-node-appd:
        condition: process_healthy

  celestia-light-node:
    command: |
      sleep 999999999
      echo "started"
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: |
          echo "true"
    liveness_probe:
      initial_delay_seconds: 10
      exec:
        command: |
          echo "true"
    depends_on:
      celestia-node-appd:
        condition: process_healthy
      celestia-bridge:
        condition: process_healthy