version: "3"

environment:

processes:

  hey-partners-soak:
    env:
      MOVEMENT_SWAP_PATH: ${MOVEMENT_SWAP_PATH}
    command: |
      LOADTEST_NUMBER_SCENARIO=1 LOADTEST_NUMBER_SCENARIO_PER_CLIENT=1 cargo test -p suzuka-client hey_partners_soak -- --nocapture
    depends_on:
      suzuka-full-node:
        condition: process_healthy
      suzuka-faucet:
        condition: process_healthy
    availability:
      exit_on_end: false # todo: revert