version: "3"

processes:

  setup:
    environment:
      - "ETH_RPC_CONNECTION_PROTOCOL=http"
      - "ETH_RPC_CONNECTION_HOSTNAME=0.0.0.0"
      - "ETH_RPC_CONNECTION_PORT=8090"
      - "ETH_WS_CONNECTION_PROTOCOL=ws"
      - "ETH_WS_CONNECTION_HOSTNAME=0.0.0.0"
      - "ETH_WS_CONNECTION_PORT=8090"
      - "MAYBE_RUN_LOCAL=true"
      - "MAYBE_TESTING_MCR=true"
      - "MAYBE_DEPLOY_MCR=true"

    command: |
      suzuka-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"
