version: "3"

environment:

processes:

  suzuka-client-tests:
    command: |
      cargo test -p suzuka-client test_example_
    depends_on:
      suzuka-full-node:
        condition: process_healthy
      suzuka-faucet:
        condition: process_healthy
    availability:
      exit_on_end: true
